name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main  # Cambia 'main' si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@54.94.38.4 << 'EOF'
            set -e
            cd /var/www/proyecto-laravel
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo systemctl restart php-fpm
            sudo systemctl restart nginx
          EOF
